apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 30m
  values:
    serviceMonitor:
      enabled: true
    certController:
      serviceMonitor:
        enabled: true
    webhook:
      replicaCount: 2
      serviceMonitor:
        enabled: true
  chart:
    spec:
      version: "0.9.5"
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      interval: 5m
