apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
spec:
  values:
    ha:
      enabled: true
    serverTelemetry:
      serviceMonitor:
        enabled: true
  chart:
    spec:
      version: "0.27.0"
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp-vault
        namespace: flux-system
      interval: 1m
