apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-nginx
  namespace: nginx
spec:
  values:
    replicaCount: 1
  interval: 10m
  chart:
    spec:
      version: "15.4.4"
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
