apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-app1
spec:
  releaseName: nginx-ingress-app1
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx/ingress-nginx
        namespace: flux-system
      version: "4.9.1"
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    controller:
    kind: Deployment
