apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx2-app2
spec:
  releaseName: nginx2
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "15.10.4"
  interval: 30m
  install:
    remediation:
      retries: 3
