apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-apache
  namespace: flux-system
spec:
  dependsOn:
    - name: helm-repositories-bitnami
    - name: namespaces
  interval: 10m0s
  path: ./flux/apps/apache
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev
  wait: true
  timeout: 15m
