apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: helm-repositories-bitnami
    - name: namespaces
  interval: 5m0s

  path: ./flux/apps/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev
  wait: true
