---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
#kind: Kustomization
#metadata:
#  name: crossplane
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: helm-repositories-crossplane
#    - name: namespaces
#  interval: 10m0s
#  path: ./flux/infrastructure/infra-apps/crossplane
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: dev
#  force: true
#  validation: client
