#apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
#kind: Kustomization
#metadata:
#  name: hashicorp-vault
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: helm-repositories-hashicorp
#    - name: namespaces
#  interval: 5m0s
#
#  path: ./flux/infrastructure/hashicorp-vault
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: dev
#  wait: true
