apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: helm-repositories-istio
    - name: namespaces
  interval: 2m0s

  path: ./flux/infrastructure/istio-operator
  prune: false
  sourceRef:
    kind: GitRepository
    name: dev
  force: true
  validation: client
