apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: helm-repositories
    - name: namespaces
  interval: 3m0s

  path: ./flux/infrastructure/istio-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev
  wait: true
