# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#  name: strimzi-podmonitor
#  namespace: flux-system
# spec:
#  dependsOn:
#    - name: namespaces
#    - name: strimzi-kafka
#  interval: 10m0s
#  path: ./flux/infrastructure/infra-apps/monitoring/strimzi-podmonitor
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: dev
#  wait: true
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
#kind: Kustomization
#metadata:
#  name: strimzi-kafka
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: namespaces
#    - name: helm-repositories-strimzi
#    - name: strimzi-kafka-operator
#  interval: 10m0s
#  path: ./flux/infrastructure/infra-apps/kafka
#  prune: false
#  sourceRef:
#    kind: GitRepository
#    name: dev
#  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
 name: strimzi-kafka-operator
 namespace: flux-system
spec:
 dependsOn:
   - name: helm-repositories-strimzi
   - name: namespaces
 interval: 10m0s
 path: ./flux/infrastructure/infra-apps/strimzi-kafka-operator
 prune: true
 sourceRef:
   kind: GitRepository
   name: flux-system
 wait: true
