apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  dependsOn:
    - name: helm-repositories-prometheus-community
    - name: namespaces
  interval: 10m0s
  path: ./flux/infrastructure/infra-apps/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev
  force: true
#  validation: client
