---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./flux/infrastructure/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev
#  force: true
#  validation: client
