apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: helm-repositories-bitnami
    - name: namespaces
  interval: 10m0s
  path: ./flux/infrastructure/infra-apps/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev
  force: true
  validation: client
