---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helm-repositories
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/infrastructure/sources
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev
  wait: true
