---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helm-repositories-istio
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/infrastructure/sources/istio
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helm-repositories-bitnami
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/infrastructure/sources/bitnami
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helm-repositories-external-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/infrastructure/sources/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helm-repositories-crossplane
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/infrastructure/sources/crossplane
  sourceRef:
    kind: GitRepository
    name: dev
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helm-repositories-keda
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/infrastructure/sources/keda
  sourceRef:
    kind: GitRepository
    name: dev
  wait: true
