---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    global:
      rbac:
        createAggregateClusterRoles: true
    metrics:
      enabled: true
    prometheus:
      prometheusSpec:
        enableRemoteWriteReceiver: true
        enableFeatures:
          - exemplar-storage
        podMonitorSelector:
          matchLabels:
            app: strimzi
        retention: 1h
        resources:
          requests:
            cpu: "0.08"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "600Mi"
        ruleSelector:
          matchLabels:
            prometheus: k8s
            role: alert-rules
        securityContext:
          fsGroup: 2000
          runAsNonRoot: true
          runAsUser: 1000
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
    grafana:
      enabled: true
      resources:
        requests:
          cpu: "0.08"
          memory: "50Mi"
        limits:
          cpu: "0.1"
          memory: "100Mi"
  chart:
    spec:
      version: "54.2.1"
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
