apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 15m
  timeout: 30m
  values:
    serviceAccount:
      create: true
      name: "mimir"
    nameOverride: "mimir"
    mimir:
      structuredConfig:
        no_auth_tenant: fake
        limits:
          ingestion_rate: 150000
          max_global_series_per_user: 0
          max_global_series_per_metric: 0
          max_label_names_per_series: 100
          compactor_blocks_retention_period: 4d
    chunks-cache:
      enabled: true
      replicas: 1

    index-cache:
      enabled: true
      replicas: 1

    metadata-cache:
      enabled: true
      replicas: 1

    results-cache:
      enabled: true
      replicas: 1
    minio:
      enabled: true
      persistence:
        size: 5Gi
    store_gateway:
      persistentVolume:
        size: 5Gi
    compactor:
      resources:
        requests:
          memory: 50Mi
          cpu: 20m
        limits:
          memory: 100Mi
      persistentVolume:
        size: 5Gi
    ingester:
      resources:
        requests:
          memory: 50Mi
          cpu: 200m
        limits:
          memory: 100Mi
      replicas: 1
      persistentVolume:
        size: 5Gi
    distributor:
      resources:
        requests:
          memory: 50Mi
          cpu: 100m
        limits:
          memory: 100Mi
      replicas: 1
    querier:
      replicas: 1
      resources:
        requests:
          memory: 50Mi
          cpu: 20m
        limits:
          memory: 100Mi
    nginx:
      autoscaling:
        enabled: true
      resources:
        requests:
          memory: 32Mi
          cpu: 20m
        limits:
          memory: 64Mi
  chart:
    spec:
      version: "4.3.0"
      chart: mimir-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
