apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: monitoring
spec:
  interval: 15m
  timeout: 30m
  values:
    mode: daemonset
    ports:
      otlp:
        enabled: true
      otlp-http:
        enabled: false
      jaeger-compact:
        enabled: false # turn on once jaeger agent is removed
      jaeger-thrift:
        enabled: false
      jaeger-grpc:
        enabled: false
      zipkin:
       enabled: false
      metrics:
        enabled: false
    config:
      exporters:
        otlp:
          endpoint: "tempo-distributed-distributor:4317"
          tls:
            insecure: true
      receivers:
        jaeger: null
        prometheus: null
        zipkin: null
      service:
        pipelines:
          traces:
            exporters:
              - otlp
            receivers:
              - otlp
          metrics: null
          logs: null
  chart:
    spec:
      version: "0.66.4"
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: flux-system
      interval: 5m
