apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apacheapp
spec:
  releaseName: apacheapp
  values:
    service:
      ## @param service.type Apache Service type
      ##
      type: clusterIP
  chart:
    spec:
      chart: apache
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "10.5.4"
  interval: 30m
  install:
    remediation:
      retries: 3
