---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
spec:
  interval: 5m
  values:
    metrics:
      enabled: true
  chart:
    spec:
      version: "2.12.1"
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
      interval: 5m
