---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-operator
  namespace: monitoring
spec:
  interval: 5m
  values:
  manager:
    image:
      repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
  chart:
    spec:
      version: "0.78.1"
      chart: opentelemetry-operator
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: flux-system
      interval: 5m
