#apiVersion: helm.toolkit.fluxcd.io/v2beta1
#kind: HelmRelease
#metadata:
#  name: istio-base
#  namespace: istio-system
#spec:
#  values:
#    enableCRDTemplates: true
#  interval: 1m
#  chart:
#    spec:
#      version: "1.17.8"
#      chart: base
#      sourceRef:
#        kind: HelmRepository
#        name: istio
#        namespace: flux-system
#      interval: 1m
#---
#apiVersion: helm.toolkit.fluxcd.io/v2beta1
#kind: HelmRelease
#metadata:
#  name: istio-operator
#  namespace: istio-system
#spec:
#  targetNamespace: istio-system
#  interval: 1m
#  values:
#    hub: gcr.io/istio-release
#    tag: 1.17.8
#  chart:
#    spec:
#      version: "1.17.8"
#      chart: ./manifests/charts/istio-operator
#      sourceRef:
#        kind: GitRepository
#        name: istio-repo
#        namespace: flux-system
#      interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator-1-18-7
  namespace: istio-system-canary
spec:
  releaseName: istio-system-canary
  targetNamespace: istio-system-canary
  interval: 1m
  values:
    operatorNamespace: istio-system-canary
    watchedNamespaces: istio-system-canary
    revision: "1-18-7"
    hub: gcr.io/istio-release
    tag: 1.18.7
  chart:
    spec:
      version: "1.18.7"
      chart: ./manifests/charts/istio-operator
      sourceRef:
        kind: GitRepository
        name: istio-base-repo-1-18-7
        namespace: flux-system
      interval: 1m
