apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: istio-repo
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/istio/istio
  ref:
    tag: 1.17.8
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/manifests/charts/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 30m
  url: https://istio-release.storage.googleapis.com/charts
