apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: cluster-controlplane
spec:
  profile: default
  tag: 1.18.7
  meshConfig:
    defaultConfig:
      # Include extra stat tags for telemetry
      extraStatTags:
        - request_url_path
        - request_tenant_id
        - request_external
      holdApplicationUntilProxyStarts: true
      tracing:
        sampling: 1.0  # Set sampling to 100% to capture all traces
    accessLogFile: /dev/stdout
    enableTracing: true
  components:
    pilot:
      k8s:
        hpaSpec:
          maxReplicas: 2
          minReplicas: 1
          behavior:
            scaleDown:
              policies:
                - periodSeconds: 120
                  type: Pods
                  value: 1
              stabilizationWindowSeconds: 300
            scaleUp:
              policies:
                - periodSeconds: 60
                  type: Pods
                  value: 1
              stabilizationWindowSeconds: 120
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
      - name: istio-tools
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 1
            maxReplicas: 2
            behavior:
              scaleDown:
                policies:
                  - periodSeconds: 120
                    type: Pods
                    value: 1
                stabilizationWindowSeconds: 300
              scaleUp:
                policies:
                  - periodSeconds: 60
                    type: Pods
                    value: 1
                stabilizationWindowSeconds: 120
#          service:
#            selector:
#              app: istio-ingressgateway
#              istio: ingressgateway
#              service.istio.io/canonical-name: istio-tools
#            loadBalancerIP: X.X.X.X # OVERLAY
#            externalTrafficPolicy: Local
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 700m # all other values are defaults, this was raised to reduce automatic HPA trigger and 100% usage
              memory: 128Mi
    telemetry:
      enabled: true
  values:
    telemetry:
      v2:
        enabled: true
        prometheus:
          enabled: true
          configOverride:
            inboundSidecar:
              disable_host_header_fallback: true
              metrics:
              - name: request_bytes
                tags_to_remove:
                - destination_canonical_service
                - destination_canonical_revision
                - destination_cluster
                - destination_principal
                - destination_service
                - destination_service_name
                - destination_version
                - pod
                - pod_name
                - source_canonical_service
                - source_canonical_revision
                - source_version
              - name: request_duration
                tags_to_remove:
                - destination_canonical_service
                - destination_canonical_revision
                - destination_cluster
                - destination_principal
                - destination_service
                - destination_service_name
                - destination_version
                - pod
                - pod_name
                - source_canonical_service
                - source_canonical_revision
                - source_version
              - name: response_bytes
                tags_to_remove:
                - destination_canonical_service
                - destination_canonical_revision
                - destination_cluster
                - destination_principal
                - destination_service
                - destination_service_name
                - destination_version
                - pod
                - pod_name
                - source_canonical_service
                - source_canonical_revision
                - source_version
              - name: requests_total
                tags_to_remove:
                - destination_canonical_service
                - destination_canonical_revision
                - destination_cluster
                - destination_principal
                - destination_service
                - destination_service_name
                - destination_version
                - pod
                - pod_name
                - source_canonical_service
                - source_canonical_revision
                - source_version
            outboundSidecar:
              disable_host_header_fallback: true
              metrics:
              - name: request_bytes
                tags_to_remove:
                - destination_canonical_service
                - destination_canonical_revision
                - destination_cluster
                - destination_principal
                - destination_service
                - destination_service_name
                - destination_version
                - pod
                - pod_name
                - source_canonical_service
                - source_canonical_revision
                - source_version
              - name: request_duration
                tags_to_remove:
                - destination_canonical_service
                - destination_canonical_revision
                - destination_cluster
                - destination_principal
                - destination_service
                - destination_service_name
                - destination_version
                - pod
                - pod_name
                - source_canonical_service
                - source_canonical_revision
                - source_version
              - name: response_bytes
                tags_to_remove:
                - destination_canonical_service
                - destination_canonical_revision
                - destination_cluster
                - destination_principal
                - destination_service
                - destination_service_name
                - destination_version
                - pod
                - pod_name
                - source_canonical_service
                - source_canonical_revision
                - source_version
              - name: requests_total
                tags_to_remove:
                - destination_canonical_service
                - destination_canonical_revision
                - destination_cluster
                - destination_principal
                - destination_service
                - destination_service_name
                - destination_version
                - pod
                - pod_name
                - source_canonical_service
                - source_canonical_revision
                - source_version
            gateway:
              disable_host_header_fallback: true
    global:
      istioNamespace: istio-system
