apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: cluster-controlplane
spec:
  profile: default
  values:
    global:
      istioNamespace: istio-system
