apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: cluster-controlplane
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        namespace: istio-apps
