#apiVersion: install.istio.io/v1alpha1
#kind: IstioOperator
#metadata:
#  namespace: istio-system
#  name: cluster-controlplane-1-19-0
#spec:
#  revision: 1-19-0
#  profile: default
#  values:
#    global:
#      istioNamespace: istio-system
