apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: kafka-rebalance-remove-broker
  namespace: strimzi-operator
  labels:
    strimzi.io/cluster: dev
  annotations:
    strimzi.io/rebalance-auto-approval: "true"
spec:
  mode: "remove-brokers"  # "full" initiates a complete rebalance; other options include "incremental" or "add_broker"
  brokers:
    - 0
