apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-cluster
spec:
  interval: 15m
  timeout: 30m
  values:
    replica:
      replicaCount: 3
    sentinel:
      enabled: true
      resources:
        requests:
          cpu: "0.05"
          memory: "200Mi"
        limits:
          cpu: "1"
          memory: "300Mi"
    auth:
      enabled: true
      password: ""
    commonConfiguration: |-
      # Disable AOF https://redis.io/topics/persistence#append-only-file
      appendonly no
      # Disable RDB persistence
      save ""
      # Max memory limit
      maxmemory 100mb
      # Evict any leased used key
      maxmemory-policy allkeys-lru
    master:
      resources:
        requests:
          cpu: "0.1"
          memory: "200Mi"
        limits:
          cpu: "0.1"
          memory: "300Mi"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          - release: "kube-prometheus"
  chart:
    spec:
      version: "17.17.1"
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 30m
